clear; clc; close all;

b_plot = 1.25;
c_plot = 0.0;
d_plot = 1.0;

NX = 80;
Nv = 40;

hX = b_plot / NX;
hv = (d_plot - c_plot) / Nv;

color_escuela = [0.0, 0.25, 0.52];
color_extrap  = 0.45*color_escuela + 0.55*[1 1 1];
color_grid    = 0.85*[1 1 1];

figure(1);
hold on;

hMallado = plot(nan, nan, '-', 'Color', color_grid, 'LineWidth', 1.2);

for i = 0:Nv
    v_i = c_plot + i*hv;
    plot([v_i v_i], [0 b_plot], '-', 'Color', color_grid, 'LineWidth', 0.8);
end

for j = 0:NX
    X_j = j*hX;
    plot([c_plot d_plot], [X_j X_j], '-', 'Color', color_grid, 'LineWidth', 0.8);
end

h1 = plot([c_plot d_plot], [0 0], '-', ...
    'Color', color_escuela, 'LineWidth', 2.6);
h2 = plot([c_plot d_plot], [b_plot b_plot], '-', ...
    'Color', color_escuela, 'LineWidth', 2.6);
h3 = plot([c_plot c_plot], [0 b_plot], '-', ...
    'Color', color_extrap, 'LineWidth', 2.6);
h4 = plot([d_plot d_plot], [0 b_plot], '-', ...
    'Color', color_extrap, 'LineWidth', 2.6);

text(-0.045, 1.25, '$0$', ...
    'Interpreter', 'latex', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle');

text(-0.045, 0.00, '$b$', ...
    'Interpreter', 'latex', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle');

text(0.00, -0.045, '$c$', ...
    'Interpreter', 'latex', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle');

text(1.00, -0.045, '$d$', ...
    'Interpreter', 'latex', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle');

text(-0.045, 0.625, '$X$', ...
    'Interpreter', 'latex', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle');

xlabel('$\upsilon$', 'Interpreter', 'latex', 'FontSize', 20);
%ylabel('$X$', 'Interpreter', 'latex', 'FontSize', 20);

legend([hMallado h3 h2], ...
    {'Mallado', 'Esq. Extrapolado', 'Cond. Front. Dirichlet'}, ...
    'Interpreter', 'latex', ...
    'FontSize', 16, ...
    'Location', 'northeast');

axis equal;
xlim([c_plot d_plot]);
ylim([0 b_plot]);

set(gca, 'XTick', []);
set(gca, 'YTick', []);
box on;
grid off;
hold off;
